version: '3'
services:
  syncpipes-server:
    image: 'sebischair/amelie:syncpipes-server'
    ports:
      - "3010:3010"
    depends_on:
      - mongoforamelie
      - rabbit
    links:
      - mongo:mongo
      - rabbit:rabbit
    environment:
      SYNCPIPES_MONGO_HOST: 'mongo'
      SYNCPIPES_RABBIT_HOST: rabbit
      SYNCPIPES_RABBIT_PORT: 5672
      SYNCPIPES_RABBIT_USER: guest
      SYNCPIPES_RABBIT_PASSWORD: guest
      SYNCPIPES_RABBIT_VHOST: '/'
  mongoforamelie:
    image: 'sebischair/amelie:mongoforamelie'
    depends_on:
      - mongo
    links:
      - mongo:mongo
  mongo:
    image: 'mongo:3.6.2'
    ports:
      - 27017:27017
  rabbit:
    image: rabbitmq:management
    ports:
      - "15671:15671"
      - "15672:15672" # management gui
      - "25672:25672"
      - "5672:5672"
      - "5671:5671"
      - "4369:4369"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest